# Generated by Django 4.2.20 on 2025-03-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
